In [ ]:
from pose_graph import PoseGraph
import numpy as np

In [ ]:
sensor_id = ["cam0", "cam1", "imu0", "imu1"]

pose_id = ["cam1", "cam2", "cam3", "cam4", "cam5"]

poses = {
    "cam1": [[1, "M"], [2, "N"], [3, "O"], [4, "P"], [5, "Q"]],
    "cam2": [(2, "N")],
    "cam3": [(3, "O")],
    "cam4": [(4, "P")],
    "cam5": [(5, "Q")],
}

# for pose in poses.items():
#     print(pose[1][1])

if 1 not in poses["cam1"]:
    print("not in")

print(poses["cam1"])


In [ ]:
edge = {"sensor": {"cam0": 1, "cam1": 2, "imu0": 3, "imu1": 4}}

# if "sensor" in edge:
#     print("yes")

# else:
#     print("no") 

# try:
#     edge["sensor"]["cam2"]
#     print("yes")
# except KeyError:
#     print("no")

if "cam0" in edge.get("sensor",{}):
    print("yes")


str1 = "cam0"

list1 = ["cam0", "cam1", "cam2", "cam3", "cam4", "cam5"]
newstr = "cam6"+str1
list1.append("cam6"+str1)
print(list1)

In [1]:
from pose_graph import PoseGraph
import numpy as np
pg = PoseGraph()

sensor_id = "1"

tf11 = np.array(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

tf12 = np.array(
    [
        [1, 0, 0, 1],
        [0, 1, 0, 2],
        [0, 0, 1, 3],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

tf13 = np.array(
    [
        [1, 0,	0,	10],
        [0,0.707106781186548,	-0.707106781186548,	2],
        [0,0.707106781186548,	0.707106781186548,	10],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

tf14 = np.array(
    [
        [0, -0.866025403784439,	0.500000000000000,	0],
        [1,     0,	0,	0],
        [0, 0.5,	0.866025403784439,	-5],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

pg.add_sensor(
    sensor_id,
    {
        "1": [tf11, True],
        "2": [tf12, True],
        "3": [tf13, True],
        # "4": [tf14, True],
    },
)

sensor_id = "5"

tf52 = np.array(
    [
        [1, 0, 0, 1],
        [0, 0, 1, -17],
        [0, -1, 0, 8],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

tf53 = np.array(
    [
        [1,	0,	0,	10],
        [0,	0.707106781186548,	0.707106781186548,	-10],
        [0,	-0.707106781186548,	0.707106781186548,	8],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

tf54 = np.array(
    [
        [0, -0.866025403784439,	0.500000000000000, 0],
        [0, 0.500000000000000,	0.866025403784439,	-25],
        [-1, 0, 0, 10],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

pg.add_sensor(
    sensor_id,
    {
        "2": [tf52, True],
        "3": [tf53, True],
        "4": [tf54, True],
    },
)

pg.update_graph(
    "1",
    {
        "2": [tf12, False],
        "3": [tf13, True],
        "4": [tf14, True],
    },
)

tf14 = pg.get_transform(parent_id="1", child_id="1", solver_method="BFS")

print(tf14)

# print(pg.object_id)
# print(pg.edges)

The object 4  is not in the graph, add it to the graph ... 
The edge between the parent node and the child node is active.
Directly return the transformation
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Test the integration of posegraph and communication functions


In [ ]:
import posehub_main
import argparse
from pose_graph import PoseGraph
import numpy as np

tf12 = np.array(
    [
        [1, 0, 0, 1],
        [0, 1, 0, 2],
        [0, 0, 1, 3],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

tf13 = np.array(
    [
        [1, 0,	0,	10],
        [0,0.707106781186548,	-0.707106781186548,	2],
        [0,0.707106781186548,	0.707106781186548,	10],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)

tf14 = np.array(
    [
        [0, -0.866025403784439,	0.500000000000000,	0],
        [1,     0,	0,	0],
        [0, 0.5,	0.866025403784439,	-5],
        [0, 0, 0, 1],
    ],
    dtype=np.float32,
)


pose_graph = PoseGraph()

tool_1_id = b"tool_1"
tool_2_id = b"tool_2"
tool_3_id = b"tool_3"

args_1 = argparse.Namespace(    
    sub_ip="10.203.150.51",
    sub_port="5588",
    pub_port="5589",
    sub_topic=[tool_1_id, tool_2_id, tool_3_id],
    pub_topic=[tool_1_id, tool_2_id, tool_3_id],
    sensor_name="h1"
    ) # args for h1 sensor

args_2 = argparse.Namespace(    
    sub_ip="10.203.150.51",
    sub_port="5589",
    pub_port="5580",
    sub_topic=[tool_1_id, tool_2_id, tool_3_id],
    pub_topic=[b"topic4", b"topic5", b"topic6"],
    sensor_name="h2"
    ) # args for h2 sensor

zmq_manager_1, sub_thread_1, pub_thread_1 = posehub_main.initialize_ZMQManager(
        args_1.sub_ip,
        args_1.sub_port,
        args_1.pub_port,
        args_1.sub_topic,
        args_1.pub_topic,
        args_1.sensor_name,
    )
zmq_manager_2, sub_thread_2, pub_thread_2 = posehub_main.initialize_ZMQManager(
        args_2.sub_ip, 
        args_2.sub_port, 
        args_2.pub_port, 
        args_2.sub_topic, 
        args_2.pub_topic,
        args_2.sensor_name
    )



pose_graph.add_sensor("h1", 
            {   "tool_1": [np.eye(4), True], 
                "tool_2": [np.eye(4), True], 
                "tool_3": [np.eye(4), True]
            }
            )

update_pose_sensor_1 = {
        "tool_1": [tf12, True],
        "tool_2": [tf13, True],
        "tool_3": [tf14, True],
}

pose_graph.update_graph("h1", update_pose_sensor_1)

i = 0
try:
    while True:
        # Running the main loop

        # test receiving poses
        # print('tool 1: ', zmq_manager_1.sub_poses['tool_1'])
        poseinfo = posehub_main.receive_poses(args_1, zmq_manager_1)
        # if not poseinfo: # if poseinfo is not empty
        if len(poseinfo) != 0:
            print("pose info from port 5588 \n ", poseinfo)
            # poseinfo should be a dictionary with key as object name and value is [pose, isActive]
            
        else:
            print("no poseinfo received")
        
        
        # print('tool 2: ', zmq_manager_1.sub_poses['tool_2'])
        # print('tool 3: ', zmq_manager_1.sub_poses['tool_3'])

        # test sending messages
        # get pose from pose graph
        for topic in args_1.pub_topic:
            # transfer the topic from bytes to string
            pose = pose_graph.get_transform("h1", topic.decode("utf-8"), solver_method="BFS")
            posehub_main.send_poses(topic,zmq_manager_1, pose)

        # test receiving poses
        poseinfo_subscribed = posehub_main.receive_poses(args_2, zmq_manager_2)
        if poseinfo_subscribed is not None:
            print("pose info from port 5589 \n ",poseinfo_subscribed)
            # poseinfo should be a dictionary with key as object name and value is [pose, isActive]
            pose_graph.update_graph("h1", poseinfo)
        else:
            print("no poseinfo received")

        i += 1e-6


except KeyboardInterrupt:
    posehub_main.terminate_ZMQManager(zmq_manager_1, sub_thread_1, pub_thread_1)
    # terminate_ZMQManager(zmq_manager_2, sub_thread_2, pub_thread_2)



In [23]:
import numpy as np
from scipy.spatial.transform import Rotation as Rot
phacon2pan = np.load('../phacon2pan_0411.npy')
pan2phacon = np.linalg.inv(phacon2pan)
tempt = pan2phacon[:3, 3]
tempR = pan2phacon[:3, :3]
convert = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
# tempR = convert@tempR
print(Rot.from_matrix(tempR).as_euler('xyz', degrees=True))
print(tempt)

[108.68643011  12.71317653 178.4865982 ]
[49.57028371 61.11514121  9.83953514]
